PipelineSecrets: {}
cleanup:
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --cleanup
controllerbuild:
  enabled: true
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --v
  - 4
  config:
    domain: pramerica.help
    exposer: Ingress
    http: "true"
jenkins:
  Servers:
    Global:
      EnvVars:
        DOCKER_REGISTRY: 118504922878.dkr.ecr.us-east-1.amazonaws.com
        TILLER_NAMESPACE: kube-system
  enabled: false
prow: {}
